apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cowrie-vm
  namespace: default
  labels:
    app: cowrie
spec:
  running: true
  template:
    metadata:
      labels:
        app: cowrie
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: cowrie/cowrie:latest
