apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowrie-deployment
  labels:
    app: cowrie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cowrie
  template:
    metadata:
      labels:
        app: cowrie
    spec:
      containers:
      - name: cowrie
        image: cowrie/cowrie:latest
        ports:
        - containerPort: 2222
        volumeMounts:
        - name: user-db
          mountPath: /cowrie/cowrie-git/etc/userdb.txt
          subPath: userdb.txt
      volumes:
      - name: user-db
        configMap:
          name: cowrie-userdb
