---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cowrie-isolation
  namespace: honeypot
spec:
  podSelector:
    matchLabels:
      app: cowrie
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - ports:
        - port: 2222
          protocol: TCP
        - port: 2323
          protocol: TCP

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: collector
      ports:
        - port: 5000
          protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: collector-policy
  namespace: honeypot
spec:
  podSelector:
    matchLabels:
      app: collector
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cowrie
      ports:
        - port: 5000
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              app: api
      ports:
        - port: 5000
          protocol: TCP

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: loki
      ports:
        - port: 3100
          protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
    - ports:
        - port: 443
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-policy
  namespace: honeypot
spec:
  podSelector:
    matchLabels:
      app: api
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - ports:
        - port: 8000
          protocol: TCP

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: collector
      ports:
        - port: 5000
          protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
