apiVersion: v1
kind: ConfigMap
metadata:
  name: cowrie-config
  namespace: honeypot
data:
  cowrie.cfg: |
    [honeypot]
    hostname = svr04
    log_path = var/log/cowrie
    download_path = var/lib/cowrie/downloads
    listen_endpoints = tcp:2222:interface=0.0.0.0

    [output_jsonlog]
    enabled = true
    logfile = /dev/stdout
