apiVersion: v1
kind: Service
metadata:
  name: cowrie-lb
  namespace: honeypot
spec:
  type: LoadBalancer
  selector:
    app: cowrie
  ports:
    - name: ssh-honey
      port: 22
      targetPort: 2222
      protocol: TCP
